### ISSUE TITLE
Facing issue while using java SDK with sample project itself..

### ISSUE THREAD

**Issue by santhozz** [testproject-io/java-sdk#48]

**Comment by santhozz** [comment]
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/testproject/sdk/drivers/web/ChromeDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at Demo.Testproject1.main(Testproject1.java:14)

Sample code for test:
package Demo;

import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeOptions;

import io.testproject.sdk.DriverBuilder;
import io.testproject.sdk.drivers.web.ChromeDriver;

public class Testproject1 {

    public static void main(final String[] args) throws Exception {
       ChromeDriver driver = new ChromeDriver(new ChromeOptions());
//    	ChromeDriver driver = new DriverBuilder<ChromeDriver>(new ChromeOptions())
//    			  .withRemoteAddress(new URL("http://localhost:8585"))
//    			  .withToken("mRZ6KJbe9NWPlnISqQAVirTnQVM47l290NE2EBScCoI1")
//    			  .build(ChromeDriver.class);
//        driver.navigate().to("https://example.testproject.io/web/");

        driver.findElement(By.cssSelector("#name")).sendKeys("John Smith");
        driver.findElement(By.cssSelector("#password")).sendKeys("12345");
        driver.findElement(By.cssSelector("#login")).click();

        boolean passed = driver.findElement(By.cssSelector("#logout")).isDisplayed();
        if (passed) {
            System.out.println("Test Passed");
        } else {
            System.out.println("Test Failed");
        }

        driver.quit();
    }
}

pom xml:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.testprojectsdk.demo</groupId>
	<artifactId>TestProjectSDKDemo</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<dependencies>
		
		<dependency>
			<groupId>io.testproject</groupId>
			<artifactId>java-sdk</artifactId>
			<version>0.64.4-RELEASE</version>
		</dependency>

	</dependencies>
</project>

let me where am wrong, so that i would correct my mistake.

**Comment by santhozz** [comment]
Let me which Java Version should i use, i would be more helpful if you share the link for direct download.

**Comment by mstrelex** [comment]
Hi @santhozz 

You can download OpenJDK 11 here: https://jdk.java.net/archive/
And this is the Windows version direct link: https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip

**Comment by mstrelex** [comment]
@santhozz Closing this, let me know if you still need assistance.
